apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-dash
  namespace: gt-dash
  labels:
    app: gt-dash
spec:
  replicas: {{ .Values.gt_dash.replicaCount }}
  selector:
    matchLabels:
      app: gt-dash
  template:
    metadata:
      labels:
        app: gt-dash
    spec:
      containers:
        - name: gt-dash
          image: {{ .Values.gt_dash.image.repository }}:{{ .Values.gt_dash.image.tag }}
          imagePullPolicy: {{ .Values.gt_dash.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gt_dash.service.port }}
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gt_dash.secretName }}
                  key: GITHUB_TOKEN
            - name: REPOS
              value: {{ .Values.gt_dash.env.repos | quote }}
            - name: WH_URL
              value: {{ .Values.gt_dash.env.webhook_url | quote }}
            - name: WH_PHONE
              value: {{ .Values.gt_dash.env.webhook_phone | quote }}
            - name: REDIS_HOST
              value: {{ .Values.gt_dash.env.redis_host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.gt_dash.env.redis_port | quote }}